server:
  port: 8123
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api

spring:
  # profiles:
  #  active: local
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  application:
    name: vision-picture-backend
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/visionpicture
    username: root
    password: 12541

  # MyBatis-Plus 配置

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 自动驼峰转换
  global-config:
    db-config:
      logic-delete-field: isDelete  # 逻辑删除字段名（实体类属性名）
      logic-delete-value: 1         # 删除标记值
      logic-not-delete-value: 0     # 未删除标记值

# Knife4j 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "视觉图片平台接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.vision.visionpicturebackend.controller
# 对象存储配置（需要从腾讯云获取）
cos:
 client:
  host: https://vision-1352574006.cos.ap-shanghai.myqcloud.com
  secretId: AKIDnzNiwynAVigeWJuIXdYGpFTUM4cbSBvW
  secretKey: Xw8A4mIerthJuOk8Xs44vfQ4Z1LZdWEm
  region: ap-shanghai
  bucket: vision-1352574006




